# Generated by Django 4.2.3 on 2023-10-20 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_remove_profile_agreement_accepted_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
