# Generated by Django 4.2.3 on 2023-10-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_options_order_nickname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='nickname',
        ),
    ]
