# Generated by Django 4.2.3 on 2023-10-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.CharField(default=1, max_length=12, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
