# Generated by Django 4.2.3 on 2023-10-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_accept_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость заказа'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price_product',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость продукта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='accept',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
