# Generated by Django 4.2.3 on 2023-07-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discription',
            field=models.TextField(default='discription'),
        ),
        migrations.AddField(
            model_name='category',
            name='link_foto',
            field=models.TextField(default='link_foto'),
        ),
        migrations.AddField(
            model_name='product',
            name='link_foto',
            field=models.TextField(default='link_foto'),
        ),
    ]
