# Generated by Django 4.2.3 on 2023-07-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_discription_category_link_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCalories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField()),
                ('proteins', models.FloatField()),
                ('fats', models.FloatField()),
                ('carbohydrates', models.FloatField()),
            ],
        ),
    ]
