# Generated by Django 4.2.3 on 2023-07-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productcalories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcalories',
            options={'verbose_name': 'БЖУ', 'verbose_name_plural': 'БЖУ'},
        ),
    ]
