# Generated by Django 4.2.3 on 2023-07-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_productcalories_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcalories',
            name='name',
            field=models.CharField(default='name', max_length=200),
        ),
    ]
