# Generated by Django 4.2.3 on 2023-10-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='category',
            name='discription',
            field=models.TextField(default='discription', verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='link_foto',
            field=models.TextField(default='link_foto', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.TextField(blank=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='link_foto',
            field=models.TextField(default='link_foto', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productcalories',
            name='calories',
            field=models.IntegerField(verbose_name='Количество калорий'),
        ),
        migrations.AlterField(
            model_name='productcalories',
            name='carbohydrates',
            field=models.FloatField(verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='productcalories',
            name='fats',
            field=models.FloatField(verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='productcalories',
            name='name',
            field=models.CharField(default='name', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productcalories',
            name='proteins',
            field=models.FloatField(verbose_name='Белки'),
        ),
    ]
