# Generated by Django 4.2.3 on 2023-10-20 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcalories',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.product'),
            preserve_default=False,
        ),
    ]
