# Generated by Django 4.2.3 on 2023-10-20 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_productcalories_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcalories',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.product'),
        ),
    ]
