# Generated by Django 4.2.3 on 2023-10-21 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_productcalories_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCalories',
        ),
    ]
